version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - //urbox/py_header_lib:/home/urbox
        container_name: py_header_lib
        restart: unless-stopped
        tty: true
        working_dir: /home/urbox
        networks:
            - urbox-networks
        ports:
            - "5000:5000"

networks:
    urbox-networks:
        driver: bridge