# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nping.proto\"\x1e\n\x0bPingRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t2+\n\x07\x41PIPing\x12 \n\x04Ping\x12\x0c.PingRequest\x1a\n.PingReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ping_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=14
  _globals['_PINGREQUEST']._serialized_end=44
  _globals['_PINGREPLY']._serialized_start=46
  _globals['_PINGREPLY']._serialized_end=74
  _globals['_APIPING']._serialized_start=76
  _globals['_APIPING']._serialized_end=119
# @@protoc_insertion_point(module_scope)
